package entity

import "time"

type Project struct {
	ID                            int64     `gorm:"column:id;primaryKey"`
	Code                          string    `gorm:"code"`
	ActivityName                  string    `gorm:"activity_name"`
	PackageName                   string    `gorm:"package_name"`
	AccountCode                   string    `gorm:"account_code"`
	AccountDescription            string    `gorm:"account_description"`
	CorporationId                 int64     `gorm:"corporation_id"`
	Executor                      string    `gorm:"executor"`
	Npwp                          string    `gorm:"npwp"`
	Director                      string    `gorm:"director"`
	Position                      string    `gorm:"position"`
	Email                         string    `gorm:"email"`
	Fax                           string    `gorm:"fax"`
	NotarisNumber                 string    `gorm:"notaris_number"`
	NotarisDate                   string    `gorm:"notaris_date"`
	NotarisName                   string    `gorm:"notaris_name"`
	RupID                         string    `gorm:"rup_id"`
	CatalogID                     string    `gorm:"catalog_id"`
	SppbjNumber                   string    `gorm:"sppbj_number"`
	SppbjDate                     string    `gorm:"sppbj_date"`
	ContractNumber                string    `gorm:"contract_number"`
	ContractDate                  string    `gorm:"contract_date"`
	ContractDateNumber            string    `gorm:"contract_date_number"`
	ContractDateLetter            string    `gorm:"contract_date_letter"`
	ContractMonth                 string    `gorm:"contract_month"`
	ContractDay                   string    `gorm:"contract_day"`
	ContractAddNumber             string    `gorm:"contract_add_number"`
	ContractAddDate               string    `gorm:"contract_add_date"`
	ContractDateAddNumber         string    `gorm:"contract_date_add_number"`
	ContractDateAddLetter         string    `gorm:"contract_date_add_letter"`
	ContractAddMonth              string    `gorm:"contract_add_month"`
	ContractAddDay                string    `gorm:"contract_add_day"`
	OrderLetterNumber             string    `gorm:"order_letter_number"`
	SpDate                        string    `gorm:"sp_date"`
	SpmkNumber                    string    `gorm:"spmk_number"`
	SpmkDate                      string    `gorm:"spmk_date"`
	ImplementationScheduleDay     string    `gorm:"implementation_schedule_day"`
	Start                         string    `gorm:"start"`
	End                           string    `gorm:"end"`
	Kelurahan                     string    `gorm:"kelurahan"`
	Kecamatan                     string    `gorm:"kecamatan"`
	SppbjValueLetter              string    `gorm:"sppbj_value_letter"`
	SppbjValue                    int64     `gorm:"sppbj_value"`
	NilaiEPurchasingOk            int64     `gorm:"nilai_e_purchasing_ok"`
	NilaiEPurchasing              int64     `gorm:"nilai_e_purchasing"`
	NilaiPembulatan               int64     `gorm:"nilai_pembulatan"`
	ContractValue                 int64     `gorm:"contract_value"`
	ContractValueLetter           string    `gorm:"contract_value_letter"`
	BusinessClassification        string    `gorm:"business_classification"`
	Volume                        int64     `gorm:"volume"`
	Unit                          string    `gorm:"unit"`
	AddendumType                  string    `gorm:"addendum_type"`
	TargetPercentage              int64     `gorm:"target_percentage"`
	ProgressPlan                  int64     `gorm:"progress_plan"`
	TotalCumulativeProgressPlan   int64     `gorm:"total_cumulative_progress_plan"`
	ActualProgress                int64     `gorm:"actual_progress"`
	TotalCumulativeActualProgress int64     `gorm:"total_cumulative_actual_progress"`
	Deviation                     int64     `gorm:"deviation"`
	Status                        string    `gorm:"status"`
	CreatedBy                     int64     `gorm:"created_by"`
	CreatedOn                     time.Time `gorm:"created_on"`
	UpdatedBy                     int64     `gorm:"updated_by"`
	UpdatedOn                     time.Time `gorm:"updated_on"`
}
